### ISSUE TITLE
Re-order non-contributory reasons

### ISSUE THREAD

**Issue by heidirehm** [clingen-data-model/clinvar-scv-curator-ext#18]
Submission errors:
New submission from submitter that appears to have been intended to update this older submission
Submitter acknowledged an error and the submission will be updated or removed

Inappropriate submissions:
Clinical significance appears to be a case-level interpretation inconsistent with variant classification

Unnecessary conflicting submissions:
VUS/LB/B claim when a mutually exclusive disease association is P/LP
Unnecessary VUS/LB/B claim for distinct condition when other interpretations are pathogenic

Lack of contradictory evidence when other submissions show valid evidence:
Older claim that does not account for recent evidence
P or LP claim with insufficient evidence to meet at least LP based on ACMG guidelines
Claim without supporting evidence provided
Conflicts with expert reviewed submission without evidence to support different classification

**Comment by larrybabb** [comment]
changed in release 1.7

**Comment by dazzariti** [comment]
Thanks, just confirmed this looks good
