### ISSUE TITLE
Add new "Action" to SCV curator extension

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#21]
Discussed on 12/10/21 call https://docs.google.com/document/d/1sh-owiIXcIvy2plmUGZ4LwD4X7A6Ghc4SSdH-rxloI8/edit?usp=sharing

Add new action "Follow up"

Offer the following reasons for a curator to select from if they choose the "Follow up" action

Follow up reasons:
Contact submitter for clarification
Flag for another curator to review
Send to VCEP to review
Other

**Comment by larrybabb** [comment]
@KelseaChang5 and/or @dazzariti could either of you update your clinvar chrome extension to the new 1.8 release and verify that the above feature is working as requested. If so, please close this out, otherwise let me know what is left to be done.

**Comment by KelseaChang5** [comment]
Installed new extension 1.8 and tested the Follow Up action with each of the listed reasons. Confirmed that it is working as expected - adds appropriate information to the CvCuration SCV Annotations sheet. Will close this ticket.
