### ISSUE TITLE
Add ability to annotate VCV only

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-scv-curator-ext#26]
At the 1/27 curator working meeting, the curators acknowledged that they need the ability to annotate the VCV with either a No Change or Follow Up action.  They discussed having to curate every SCV on a VCV as "no change" or "follow up" but quickly determined that was not a reasonable solution.

DoD: When the Clinvar Curator chrome extension allows the user to select the VCV from the bottom of the drop down list. When a VCV is selected it should show the agg interp, agg review status and agg last eval date in the extensions selection window. When a VCV is selected it should only allow the Follow Up or No Change action to be selected, with the same reasons as the SCV for those two actions, and it should allow Notes.  When a VCV annotation is submitted it should append an entry to the VCVs tab in the same google sheet as the SCVs.

**Comment by larrybabb** [comment]
@KelseaChang5 once you verify that the DoD description above is met, can you close this? If there's any questions or bugs please re-assign it to me and let me know what they are.

**Comment by KelseaChang5** [comment]
@larrybabb Verified that all of the elements of the VCV curation is present and outlined as it should be above. 
However, I noticed that when doing SCV curations, the submitter ID now comes up as "undefined". I tried this for a couple of entries of well established labs and they all seem to show up the same. I have attached a screenshot below of this and also left these entries on the sheet for now and will delete them after you no longer need them.![Screen Shot 2022-01-31 at 9.08.33 AM.png](https://images.zenhubusercontent.com/6189303ebad10a9727d59b63/37e1e4d8-a718-4b9a-a67d-4a7b91442a29)

**Comment by larrybabb** [comment]
re-download and try again. I updated the same release id v1.9. Normally I would do a beta version and then wait for testing to release this, but this seemed so minor that i just went for it. Now I'm updating releases, which is not ideal. Oh well. next time I'll try to be smarter about it.

**Comment by KelseaChang5** [comment]
@larrybabb I re-downloaded and tried again, but unfortunately I am still getting _undefined_ under Submitter ID

**Comment by larrybabb** [comment]
@KelseaChang5 would you please try to re-download again and test?

**Comment by KelseaChang5** [comment]
Looks good now! Closing ticket
