### ISSUE TITLE
Updating "Follow up" reasons in Chrome extension

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#35]
Heidi would like to replace the Follow Up Reason "Send to VCEP to review" with two options:
-Send to VCEP for full review
-Send to VCEP for triage

Current "Follow Up" Action reasons include
-Contact submitter for clarification
-Flag for another curator to review
-Send to VCEP to review (remove)
-Other

Request:

The "Follow Up" Action reasons list should look like this:
-Contact submitter for clarification
-Flag for another curator to review
-Send to VCEP for full review (new)
-Send to VCEP for triage (new)
-Other

**Comment by larrybabb** [comment]
@dazzariti should I translate any existing "Send to VCEP to review" Follow up actions with one of the two new replacements? Or just leave them as-is? 

Here's what's in the curated data so far...

```
SCV000892401.8 | CeGaT Praxis fuer Humangenetik Tuebingen | Likely pathogenic | Follow Up | Send to VCEP to review | thought to be hypomorphic variant and should be assessed for macular dystrophy
SCV000546418.6 | Invitae | Likely pathogenic | Follow Up | Send to VCEP to review |  
SCV001136772.2 | Mendelics | Likely pathogenic | Follow Up | Send to VCEP to review |  
SCV001335308.1 | ClinGen RASopathy Variant Curation Expert Panel | Uncertain significance | Follow Up | Send to VCEP to review | See my email to RASopathy VCEP
SCV000194689.1 | Genetic Services Laboratory,University of Chicago | Pathogenic | Follow Up | Send to VCEP to review | There is too much conflict for this variant. I can't mark anything noncontributory. VCEP should evaluate.
SCV002059080.1 | 3billion | Likely pathogenic | Follow Up | Send to VCEP to review | Too much conflict; VCEP should evaluate.
```

**Comment by larrybabb** [comment]
@dazzariti will verify the new release 1.9.3 and close this request if all is working as expected.

**Comment by dazzariti** [comment]
Perfect!
