### ISSUE TITLE
Update SCV "Reasons"

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#39]
Replace existing "Follow Up" Reasons with the following list:

Send for submitter review
Send for another curator to review
Send for VCEP triage
Send for VCEP full review
Other

Changes to "Non-contributory" reasons:

- Change "Claim without supporting evidence" to "Claim with insufficient supporting evidence"
- Add a new reason "Outlier claim with insufficient supporting evidence"

Discussed at September 13 CvC Check In meeting and on Slack

**Comment by larrybabb** [comment]
@dazzariti There are 25 Follow Up curations with the reason 'Contact submitter for clarification'. How will these be translated to the new list. It appears as if you either forgot this item in the new request or you have some intention to remove or translate these existing curations in a way that is not specified. Please clarify.

**Comment by larrybabb** [comment]
@dazzariti Under which subheader should I add the new Non-contributory reason `Outlier claim with insufficient supporting evidence`?

**Comment by larrybabb** [comment]
per @heidi I am addint the `Outlier claim...` under the last subgroup for the non-contributory reasons.  And, the `Contact submitter for clarification` is being merged into the `Send for submitter review` Follow-Up reason.

**Comment by larrybabb** [comment]
@dazzariti and/or @hdziadzio can you please verify that the new 1.9.5 chrome extension satisfies the request above. If so, please close this issue. If not, please specify what the remaining issue is.

**Comment by dazzariti** [comment]
Looks good to me!
