### ISSUE TITLE
Remove non-contributory reason

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#42]
Remove the non-contributory reason "VUS/LB/B claim when a mutually exclusive disease association is P/LP" from reason list

**Comment by larrybabb** [comment]
@dazzariti What should I do with the 20 curations that have the Non-Contributory reason `VUS/LB/B claim when a mutually exclusive disease association is P/LP`?   Should these be translated to the only remaining `Unnecessary conflicting submissions` reason `Unnecessary VUS/LB/B claim for distinct condition when other interpretations are pathogenic`?
