### ISSUE TITLE
VCV-level Actions - Follow Up Reasons

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#44]
Remove the "Send for submitter review" Follow Up Reason

Remove: Send for submitter review
Keep: Send for another curator to review
Keep: Send for VCEP triage
Keep: Send for VCEP full review
Other

**Comment by dazzariti** [comment]
Additional information from Heidi on Slack:

If we only look at one SCV, we just mark it at the SCV level, but if we look at everything and want to say no change on everything, we mark it at the VCV level and it extends to all.

I think that if someone new comes in and marks a VCV as 'no change' that that should extend to all SCVs, even if one was marked something else in the past. If we have ability to make this more sophisticated (e.g. some sort of alert/warning so you know that you are overriding a older flag), that's even better but I realize we may not have the bells and whistles!

**Comment by larrybabb** [comment]
@dazzariti I noticed that Julie R is adding tons of VCV related curations via the chrome extension. Does that mean that this ticket should take precedence over anything else above?

I think you and I should sync for 15m each week before the standup to make sure my priorities are in order for anything that you and I are working on.

**Comment by dazzariti** [comment]
Thanks Larry - can you let me know what times generally work for you for a weekly sync up?

Julie is now focusing on VCVs as discussed with Heidi, but this ticket is not blocking her work.

**Comment by dazzariti** [comment]
Just sent a hold

**Comment by dazzariti** [comment]
This ticket no longer needed based on our discussion today - I'm closing.
