### ISSUE TITLE
Chrome Extension Updates

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#57]
As discussed on Aug 21st CvC Check in call - we would like to make the following changes to the Chrome extension (summarized here, laid out in detail in the attached Google doc)

- [x] Remove VCV- level options - Remove ability to annotate a VCV - top menu should be limited to “Select an SCV” and only SCVs should be listed. No actions should be available for VCVs.
- [x] Remove SCV-Level “Follow Up” Action and all associated reasons
- [x] Update “Reason” options for SCV-level Non Contributory Actions

Full specifications here https://docs.google.com/document/d/1-ej7Oql8XHSJFEK03YFVzdh3u64aUFjsuNmb1BWJ2IA/edit?usp=sharing

**Comment by larrybabb** [comment]
release v1.9.7 and v2.0.1 both have the updates for this ticket.

**Comment by dazzariti** [comment]
The only thing missing from 1.9.7 is the Category names for the contributory reasons - I think those are only displayed in the extension, not captured in the annotation - I'll highlight them in the document

**Comment by larrybabb** [comment]
TY - please retry with release 1.9.8 and/or 2.0.2 https://github.com/clingen-data-model/clinvar-scv-curator-ext/releases/tag/1.9.8

**Comment by dazzariti** [comment]
Looks good!
