### ISSUE TITLE
Update old Non Contributory Reasons 

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-scv-curator-ext#58]
Once the changes requested in https://github.com/clingen-data-model/clinvar-scv-curator-ext/issues/57 go through - the Non-contributory existing annotations should be mapped as follows

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6ae845ec-7fff-9bdf-972a-6973637f6c0f"><div dir="ltr" style="margin-left:-5.25pt;" align="left">

Previous Reason: | Map to:
-- | --
Submitter acknowledged an error and the submission will be updated or removed | Other submission error
VUS/LB/B claim when mutually exclusive disease associations is P/LP | Unnecessary conflicting claim for distinct condition when other classifications are more relevant
Unnecessary VUS/LB/B Claim for distinct condition when other interpretations are Pathogenic | Unnecessary conflicting claim for distinct condition when other classifications are more relevant
P or LP claim with insufficient evidence to meet at least LP based on ACMG guidelines | Claim with insufficient supporting evidence

</div></b>

Full details here https://docs.google.com/document/d/1NrClZQ8eweWlRGCMDZGXr6SHBKFASv3NEUF82g3exSc/edit?usp=sharing

**Comment by larrybabb** [comment]
Completed Step 1 - update historical data source in CvCuration Annotations google sheet by replacing reason text above. And, manually "retire" all "Follow Up" and "Override" action curations as of 08-24-2023 so they no longer impact reports.

**Comment by larrybabb** [comment]
created version 1.9.7 for the older form of the extension and 2.0.1 for the newer form. The older form still works even though Google states that it will soon prevent (v2 manifests) from working. The newer form (v3 manifest) works identically except that the chrome popup window does not close after submitting.  (still trying to figure that out). The users can continue using 1.9.7 until it no longer works.

**Comment by larrybabb** [comment]
@dazzariti please update and verify it is working as this ticket describes. if so, please close, if not, please specify any remaining issues.

**Comment by dazzariti** [comment]
Looks good!
